import { COLORS } from "@/constants/theme";
import { StyleSheet} from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0',
  },
  topNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.blue,
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  backButton: {
    padding: 8,
  },
  userInfo: {
    alignItems: 'center',
  },
  userName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    paddingBottom: 5,
  },
  userStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  onlineIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CAF50',
    marginRight: 5,
  },
  userStatusText: {
    color: '#fff',
    marginLeft: 5,
    fontSize: 12,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesList: {
    padding: 16,
  },
  messageGroup: {
    marginVertical: 4,
  },
  chartButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chartButtonText: {
    color: '#fff',
    marginLeft: 5,
  },
  dateHeader: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  dateText: {
    color: '#757575',
    fontSize: 14,
  },
  chatArea: {
    flex: 1,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  infoMessage: {
    backgroundColor: '#e0f7fa',
    borderRadius: 8,
    padding: 10,
    marginVertical: 5,
    alignSelf: 'center',
  },
  infoText: {
    color: '#00acc1',
    fontSize: 14,
    textAlign: 'center',
  },
  userMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginVertical: 5,
  },
  userMessageWrapper: {
    alignItems: 'flex-end',
    marginRight: 8,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  userMessageBubble: {
    backgroundColor: COLORS.blue,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    padding: 12,
    maxWidth: 280,
  },
  userText: {
    fontSize: 16,
    color: '#fff',
  },
  userMessageTime: {
    fontSize: 11,
    color: '#666',
    marginTop: 4,
  },
  userImageBubble: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderBottomRightRadius: 4,
    padding: 4,
    maxWidth: 280,
  },
  userImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
  },
  imageCaptionContainer: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    right: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 8,
    padding: 8,
  },
  imageCaptionText: {
    color: '#fff',
    fontSize: 14,
  },
  systemMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    marginVertical: 5,
  },
  systemAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  systemMessageWrapper: {
    alignItems: 'flex-start',
  },
  badgeMessage: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 10,
    marginVertical: 5,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  highlightedBadge: {
    backgroundColor: '#fff8e1',
  },
  badgeIcon: {
    marginRight: 8,
  },
  badgeText: {
    color: '#546e7a',
    fontSize: 14,
    flexShrink: 1,
  },
  systemMessage: {
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    padding: 12,
    maxWidth: 280,
  },
  systemIcon: {
    marginRight: 8,
  },
  systemText: {
    color: '#333',
    fontSize: 14,
  },
  systemMessageTime: {
    fontSize: 11,
    color: '#666',
    marginTop: 4,
  },
  typingIndicator: {
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    padding: 12,
    maxWidth: 280,
  },
  typingDots: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#999',
    marginHorizontal: 2,
  },
  messageTime: {
    fontSize: 12,
    color: '#757575',
    marginTop: 5,
    paddingLeft: 5,
  },
  inputArea: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingVertical: 8,
    paddingHorizontal: 14,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  imagePreviewContainer: {
    paddingBottom: 12,
  },
  imagePreview: {
    position: 'relative',
  },
  previewImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  removeImageButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ff4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  input: {
    flex: 1,
    minHeight: 38,
    maxHeight: 110,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginHorizontal: 6,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#F9FAFB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
  },
  sendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  mediaButtonsContainer: {
    flexDirection: 'row',
    marginRight: 10,
    marginBottom: 10,
  },
  mediaButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F0F4F8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1.5,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    marginVertical: 5,
  },
  loadingText: {
    marginLeft: 10,
    color: '#42a5f5',
    fontSize: 14,
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
});