import { COLORS } from "@/constants/theme";
import { StyleSheet,Dimensions} from "react-native";

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 15,
    paddingTop: 15,
  },
  scrollContentContainer: {
    paddingBottom: 20,
    flexGrow: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
    width: '100%', 
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.blue,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#777',
    textAlign: 'center',
    marginBottom: 15,
  },
  deviceListContainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    width: '90%', 
  },
  deviceListTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 8,
    marginBottom: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
    width: '100%',
  },
  selectedListItem: {
    borderColor: '#00aaff',
    backgroundColor: '#e0f7fa',
  },
  logo: {
    width: 50,
    height: 50,
    marginRight: 12,
    resizeMode: 'contain',
  },
  listItemText: {
    flex: 1,
    fontSize: 15,
    color: '#333',
  },
  instructionsContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    width: '90%', 
  },
  instructionsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  instructionsText: {
    fontSize: 15,
    color: '#555',
    marginBottom: 10,
    textAlign: 'center',
    lineHeight: 22,
  },
  icon: {
    marginRight: 8,
  },
  connectButton: {
    backgroundColor: COLORS.blue,
    paddingVertical: 12, 
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2, 
    shadowRadius: 2, 
    elevation: 1, 
  },
  connectingButton: {
    backgroundColor: '#ffc107',
    shadowOpacity: 0.1, 
  },
  connectedButton: {
    backgroundColor: '#28a745',
    shadowOpacity: 0.1, 
  },
  connectButtonText: {
    color: '#fff',
    fontSize: 16, 
    fontWeight: 'bold',
  },
  statusContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eee',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 0.5,
    width: '90%', 
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
    marginBottom: 8,
  },
  successText: {
    fontSize: 15,
    color: '#28a745',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 15,
    color: '#dc3545',
    alignItems: 'center',
  },
});